# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_auto_20160803_2238'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a is employer or not', verbose_name='is_employer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_job_seekers',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a is employer or not', verbose_name='is_employer'),
        ),
    ]
