# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0008_offer_company_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
