# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0013_auto_20160917_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lieu',
            field=models.CharField(blank=True, choices=[(b'ariana', 'Ariana'), (b'beja', 'Beja'), (b'ben arous', 'Ben Arous'), (b'bizert', 'Bizert'), (b'gabes', 'Gabes'), (b'gafsa', 'Gafsa'), (b'jendouba', 'Jendouba'), (b'kairouan', 'Kairouan'), (b'kasserine', 'Kasserine'), (b'kebili', 'Kebili'), (b'kef', 'Kef'), (b'mahdia', 'Mahdia'), (b'manouba', 'Manouba'), (b'medenine', 'Medenine'), (b'monastir', 'Monastir'), (b'nabeul', 'Nabeul'), (b'sfax', 'Sfax'), (b'sidi bouzid', 'Sidi Bouzid'), (b'siliana', 'Siliana'), (b'sousse', 'Sousse'), (b'tataouine', 'Tataouine'), (b'tozeur', 'Tozeur'), (b'tunis', 'Tunis'), (b'zaghouan', 'Zaghouan')], max_length=255, null=True),
        ),
    ]
