# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0015_applyoffer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applyoffer',
            unique_together=set([('offer', 'user')]),
        ),
    ]
